# Generated by Django 4.2.5 on 2023-09-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='WatchList',
            new_name='watchList',
        ),
    ]
