# Generated by Django 4.2.5 on 2023-09-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_rename_watchlist_review_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='watchList',
            new_name='watchlist',
        ),
    ]
