# Generated by Django 4.2.5 on 2023-09-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_review_reviewer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer_user',
            new_name='review_user',
        ),
    ]
